language: node_js
node_js: 
  - 8.9.1

# Travis-CI Caching
cache:
  directories:
    - node_modules


before_script:
  # - npm install -g hexo-cli


install:
  - npm install


script:
  - hexo g
  
# 设置git提交名，邮箱；替换真实token到_config.yml文件，最后depoy部署
after_script:
  - cd ./public
  - git init
  - git config user.name "hansenwangvip"
  - git config user.email "hansenwangvip@gmail.com"
  - git add .
  - git commit -m "Update docs with Travis CI."
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master


branches:
  only:
    - hexo
env:
 global:
   - GH_REF: github.com/hansenwangvip/hansenwangvip.github.io.git